#!/bin/busybox sh

mount -a                  # Mount all mounts listed in /etc/fstab
mdev -s                   # Populate /dev
hostname -F /etc/hostname # Set hostname
ifconfig lo 127.0.0.1 up  # Initialize loopback

cat /etc/motd

